spring.application.name=HN-KS24-CNTT1-IT210-TranHuuNhat-Project
spring.datasource.url=jdbc:mysql://localhost:3306/HN_KS24_CNTT1_IT210_TranHuuNhat_Project?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Huunhat@200506
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

